name: CI

on: [push]

jobs:
  build:
    name: Code Coverage
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: [ 8.1 ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up PHP ${{ matrix.php-version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODE_COV_TOKEN }}
          fail_ci_if_error: true
          files: ./clover.xml
