name: CI

on: [push]

jobs:
  build:
    name: Code Coverage
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: [ 8.1 ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODE_COV_TOKEN }}
          verbose: true
          files: ./clover.xml
