name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v1

      - name: Setup PHP with Xdebug
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          coverage: xdebug
          tools: phpunit:9.5
          configuration: phpunit.xml
          bootstrap: vendor/autoload.php

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


      - name: Run Test
        run : vendor/bin/phpunit --configuration phpunit.xml --bootstrap vendor/autoload.php --test-suffix Test.php,.phpt -d memory_limit=256M tests --coverage-clover ./coverage.xml

      - name: Upload to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODE_COV_TOKEN }}
          files: ./coverage.xml
          verbose: true