name: Test Suite
on: [push]

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout to code repo
        uses: actions/checkout@v2

      - name: Setup PHP with Xdebug
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"
          coverage: xdebug
      - name: Install composer and dependencies
        uses: php-actions/composer@v6

      - name: PHPUnit Tests
        uses: php-actions/phpunit@v3
        env:
            XDEBUG_MODE: coverage
        with:
            bootstrap: vendor/autoload.php
            configuration: phpunit.xml
            php_extensions: xdebug
            args: tests --coverage-clover ./coverage.xml

      - name: Upload Code Coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          flags: unit_tests
          name: codecov-umbrella
          fail_ci_if_error: true
          verbose: true
